---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9102 is listening
      ansible.builtin.wait_for:
        port: 9102

    - name: Test configuration for warnings
      ansible.builtin.command:
        cmd: bareos-fd --test-config
      become_user: bareos
      register: bareos_fd_test_config
      failed_when:
        - bareos_fd_test_config.stdout_lines is search("There are configuration warnings")
